### ISSUE TITLE
Purchase of materials

### ISSUE THREAD

**Issue by IbrahimAmrIbrahim** [IbrahimAmrIbrahim/ASUMobiCarG15#25]
### We need to buy :

|  Component | No. of Items |
|  :------: | :------: |
|  4WD Smart Robot Car Chassis Kits | 1 |
|  Arduino Mega 2560 R3 (latest Revision) | 1 |
|  H-Bridge L298 (2A Dual Motor Driver) | 1 |
|  Serial Bluetooth Module (Master/Slave) | 1 |
|  Ultrasonic Sensor Module | 1 |
|  Ultrasonic Sensor Mounting Bracket Holder for HC-SR04 , Big | 1 |
|  Battery GTL 18650 5000mAh (Blue) | 3 |
|  Battery Charger | 1 |
|  Micro Servo Motor  | 1 |
|  Line Follower Sensor - Digital  | 5 |
|  IMU (3 Axis Gyro + 3 Axis Accelorometer ) MPU-6050 | 1 |

**Comment by AhmedAshraf98** [comment]
done

**Comment by AhmedHessuin** [comment]
done

**Comment by ahmedkhairy97** [comment]
done
