### ISSUE TITLE
Easy Driving Code

### ISSUE THREAD

**Issue by IbrahimAmrIbrahim** [IbrahimAmrIbrahim/ASUMobiCarG15#26]
### We need to achieve:

* Submit special Bluetooth command to put the car in easy driving mode.
* Control car movement using mobile.
* Move the car forward, backward, left and right.

**Comment by IbrahimAmrIbrahim** [comment]
Done 👍  :smirk:

**Comment by Medhaat** [comment]
Done :stuck_out_tongue_winking_eye:
