### ISSUE TITLE
Obstacles Avoidance

### ISSUE THREAD

**Issue by IbrahimAmrIbrahim** [IbrahimAmrIbrahim/ASUMobiCarG15#27]
### We need to achieve:

* The car should avoid obstacles. 
* The minimum requirements of obstacle avoidance is stop to avoid collision.
* Better avoidance techniques.

**Comment by AhmedAshraf98** [comment]
done

**Comment by AhmedHessuin** [comment]
Done

**Comment by ahmedkhairy97** [comment]
Done
