### ISSUE TITLE
Line Tracking Application

### ISSUE THREAD

**Issue by IbrahimAmrIbrahim** [IbrahimAmrIbrahim/ASUMobiCarG15#45]
When the car placed over the track it should follow the line.
* The minimum requirements is to use simple closed track.
* Bonus, for complex tracks with crossing points and sharp curves of radius less than 25 cm.

![Image of Line Tracking](https://github.com/IbrahimAmrIbrahim/ASUMobiCarG15/blob/master/Images/Line%20Traking.png)

**Comment by Medhaat** [comment]
Done

**Comment by IbrahimAmrIbrahim** [comment]
Done 😄  :relaxed:
