### ISSUE TITLE
Accurate Movement Application

### ISSUE THREAD

**Issue by IbrahimAmrIbrahim** [IbrahimAmrIbrahim/ASUMobiCarG15#46]
- [x] User can order the car to move forward or backward for certain length (EX 40 cm).
- [x] Use can order the car to move right with proper angle (EX 30 degree).
- [x] While demo the car should move in infinity shape then rectangle shape then circle shape.
* The car should return to beginning point after finishing each shape.
* The car should stop for 25 seconds after finishing each shape.
* The shape size must be (2m x 2m) no more no less.

**Comment by AhmedAshraf98** [comment]
Done
